
#### 1차원 배열 연결하고 분리하기
```python
>>> X = np.array([1,2,3])
>>> Y = np.array([4,5,6])
>>> np.column_stack([X, Y])
# array([[1, 4],
#        [2, 5],    
#        [3, 6]])
```
```python
>>> np.vstack([X, Y])
# array([[1, 2, 3],
#        [4, 5, 6]])

>>> np.hstack([X, Y])
# array([1, 2, 3, 4, 5, 6])

np.stack([X, Y])
# array([[1, 2, 3],
#        [4, 5, 6]])

>>> np.concatenate([X, Y])
# array([1, 2, 3, 4, 5, 6])

>>> np.hsplit(X, 3)
# [array([1]), array([2]), array([3])]
```

#### 2차원 배열 분리하기
```python
>>> X = np.array([[1,2],
                  [3,4]])

>>> Y = np.array([[5,6],
                  [7,8]])

>>> x_1, x_2 = np.hsplit(X, 2)

>>> x_1
# array([[1],
#        [3]])

>>> x_2
# array([[2],
#        [4]])

>>> x_1, x_2 = np.vsplit(X, 2)

>>> x_1
# array([[1, 2]])

>>> x_2
# array([[3, 4]])
```

#### 2차원 배열 연결하기
```python

>>> X = np.array([[1,2],
                  [3,4]])

>>> Y = np.array([[5,6],
                  [7,8]])

>>> np.column_stack([X, Y])
# array([[1, 2, 5, 6],
#        [3, 4, 7, 8]])

>>> np.hstack([X, Y])
# array([[1, 2, 5, 6],
#        [3, 4, 7, 8]])

>>> np.vstack([X, Y])
# array([[1, 2],
#        [3, 4],
#        [5, 6],
#        [7, 8]])

>>> np.stack([X,Y])
# array([[[1, 2],
#         [3, 4]],
#        [[5, 6],
#         [7, 8]]])

>>> np.stack([X,Y], axis=1)
# array([[[1, 2],
#         [5, 6]],
#        [[3, 4],
#         [7, 8]]])


>>> np.concatenate([X, Y])
# array([[1, 2],
#        [3, 4],
#        [5, 6],
#        [7, 8]])

>>> np.concatenate([X, Y], axis=1)
# array([[1, 2, 5, 6],
#        [3, 4, 7, 8]])
```

#### 기타
```python
# X의 view를 생성합니다.
>>> X.view()   
# 배열 X의 복사본을 만듭니다.
>>> np.copy(X) 
# 배열 X의 깊은 복사본을 만듭니다.
>>> X.copy()   

>>> X = np.array([[15, 25, 13],
                  [40, 5, 6]])
                  
>>> X.sort(axis=0)

>>> X
# array([[15,  5,  6],
#        [40, 25, 13]])

>>> X = np.array([[15, 25, 13],
                  [40, 5, 6]])

>>> X.sort(axis=1)

>>> X
# array([[13, 15, 25],
#        [ 5,  6, 40]])
```



#### 난수 샘플링
```python
>>> np.random.randint(0, 10, 
                size=(2, 2))
# array([[4, 0],
#        [3, 7]])

>>> np.random.uniform(0, 10, 
                size=(2, 2))
# array([[4.46332442, 7.87813018],
#        [7.34122875, 2.58404293]])

>>> np.random.normal(loc=0, 
                     scale=1, 
                     size=(2,2))
# array([[ 0.11727884, -0.27276952],
#        [ 0.11902775, -0.05845022]])
```


#### 배열 모양바꾸기 (1)
```python
>>> X = np.array([[1,2,3],
                  [4,5,6]])

>>> np.expand_dims(X, 0)
# array([[[1, 2, 3],
#         [4, 5, 6]]])

>>> np.expand_dims(X, 1)
# array([[[1, 2, 3]],
#        [[4, 5, 6]]])

>>> np.expand_dims(X, 2)
# array([[[1], [2], [3]],
#        [[4], [5], [6]]])

>>> X = np.array([[1,2,3]])

>>> X.squeeze(0)
# array([1, 2, 3])

>>> X = np.array([[1],[2],[3]])

>>> X.squeeze()
# array([1, 2, 3])
```

#### 배열 모양바꾸기 (2)
```python
>>> X.reshape(3, 2)
# array([[1, 2],
#        [3, 4],
#        [5, 6]])

"""
-1 을 넣으면 해당 차원의 크기는 
자동으로 조정됩니다.
만약 reshape(-1,1)을 호출한다면, 
행은 알아서 하고, 열의 사이즈만
1로 맞추어 달라고 요구하는 것과
같습니다!
"""
>>> X.reshape(-1, 1)
# array([[1],
#        [2],
#        [3],
#        [4],
#        [5],
#        [6]])

>>> X.reshape(1, -1)
# array([[1, 2, 3, 4, 5, 6]])

X.reshape(-1)
# array([1, 2, 3, 4, 5, 6])

>>> X.flatten()
# array([1, 2, 3, 4, 5, 6])
```

#### 배열 생성
```python
>>> np.array([.1, .2, .3],
             dtype=np.float32)
# array([0.1, 0.2, 0.3], 
#       dtype=float32)

>>> np.array([[.1, .2, .3,],
              [.4, .5, .6]],
              dtype=np.float32)
# array([[0.1, 0.2, 0.3],
#        [0.4, 0.5, 0.6]], 
#        dtype=float32)

>>> np.zeros((2, 3), dtype=np.int8)
# array([[0, 0, 0],
#        [0, 0, 0]], dtype=int8)

>>> np.ones((2, 3))
# array([[1., 1., 1.],
#        [1., 1., 1.]])

>>> np.full((2, 3), 10)
# array([[10, 10, 10],
#        [10, 10, 10]])

>>> np.arange(1, 3, 0.5)
# array([1. , 1.5, 2. , 2.5])

>>> np.linspace(1, 3, 5)
# array([1. , 1.5, 2. , 2.5, 3. ])

>>> np.eye(3)
# array([[1., 0., 0.],
#        [0., 1., 0.],
#        [0., 0., 1.]])

>>> np.diag([1,2,3])
# array([[1, 0, 0],
#        [0, 2, 0],
#        [0, 0, 3]])
```

#### 연산
```python
>>> X = np.array([[1.0,2.0],
                  [3.0,4.0]])

>>> np.multiply(X, X)
# array([[ 1.,  4.],
#        [ 9., 16.]])

>>> np.matmul(X, X)
# array([[ 7., 10.],
#        [15., 22.]])

>>> X.transpose()
# array([[1., 3.],
#        [2., 4.]])

>>> X.sum()
# 10.0

>>> X.sum(axis=0)
# array([4., 6.])

>>> X.sum(axis=1)
# array([3., 7.])

>>> X.mean(axis=0)
# array([2., 3.])
```


#### 인덱싱
```python
>>> X = np.array([[1,2,3],
                  [4,5,6]])

>>> X[1,0] 
# 4

>>> X[1,0:2]
# array([4, 5])


"""
아래의 결과는 Fancy Indexing으로
X[1,0], X[0,1], X[1,2], X[1,1]을 
차례대로 나열한 것입니다.
"""
>>> X[[1,0,1,1], 
      [0,1,2,1]]
# array([4, 2, 6, 5])

>>> X < 3
# array([[ True,  True, False],
#        [False, False, False]])

>>> X[X<3]
# array([1, 2])
```

#### 배열의 저장 및 불러오기
```python
>>> X = np.array([[1,2,3],
                  [4,5,6]])

>>> np.save("X.npy", X)

>>> np.savez("X.npz", 
              col1=X[:,0], 
              col2=X[:,1])

>>> np.load("X.npy")
# array([[1, 2, 3],
#        [4, 5, 6]])

>>> arrs = np.load("X.npz")

>>> arrs["col1"] 
# array([1, 4])

>>> arrs["col2"]
# array([2, 5])

>>> np.savetxt("X.csv", 
                X, 
                delimiter=",")

>>> np.loadtxt("X.csv", 
                delimiter=",")
# array([[1., 2., 3.],
#        [4., 5., 6.]])
```

